ERROR 2019-01-21 10:06:14 _log Exception: Error reading SSH protocol banner
ERROR 2019-01-21 10:06:14 _log Traceback (most recent call last):
ERROR 2019-01-21 10:06:14 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2044, in _check_banner
ERROR 2019-01-21 10:06:14 _log     buf = self.packetizer.readline(timeout)
ERROR 2019-01-21 10:06:14 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
ERROR 2019-01-21 10:06:14 _log     buf += self._read_timeout(timeout)
ERROR 2019-01-21 10:06:14 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/packet.py", line 555, in _read_timeout
ERROR 2019-01-21 10:06:14 _log     raise socket.timeout()
ERROR 2019-01-21 10:06:14 _log socket.timeout
ERROR 2019-01-21 10:06:14 _log 
ERROR 2019-01-21 10:06:14 _log During handling of the above exception, another exception occurred:
ERROR 2019-01-21 10:06:14 _log 
ERROR 2019-01-21 10:06:14 _log Traceback (most recent call last):
ERROR 2019-01-21 10:06:14 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1893, in run
ERROR 2019-01-21 10:06:14 _log     self._check_banner()
ERROR 2019-01-21 10:06:14 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2049, in _check_banner
ERROR 2019-01-21 10:06:14 _log     'Error reading SSH protocol banner' + str(e)
ERROR 2019-01-21 10:06:14 _log paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR 2019-01-21 10:06:14 _log 
ERROR 2019-01-21 10:06:14 connect 用户Administrator通过webssh连接10.1.19.12失败！原因：Error reading SSH protocol banner
ERROR 2019-01-21 10:06:48 _log Exception: Error reading SSH protocol banner
ERROR 2019-01-21 10:06:48 _log Traceback (most recent call last):
ERROR 2019-01-21 10:06:48 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2044, in _check_banner
ERROR 2019-01-21 10:06:48 _log     buf = self.packetizer.readline(timeout)
ERROR 2019-01-21 10:06:48 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
ERROR 2019-01-21 10:06:48 _log     buf += self._read_timeout(timeout)
ERROR 2019-01-21 10:06:48 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/packet.py", line 555, in _read_timeout
ERROR 2019-01-21 10:06:48 _log     raise socket.timeout()
ERROR 2019-01-21 10:06:48 _log socket.timeout
ERROR 2019-01-21 10:06:48 _log 
ERROR 2019-01-21 10:06:48 _log During handling of the above exception, another exception occurred:
ERROR 2019-01-21 10:06:48 _log 
ERROR 2019-01-21 10:06:48 _log Traceback (most recent call last):
ERROR 2019-01-21 10:06:48 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1893, in run
ERROR 2019-01-21 10:06:48 _log     self._check_banner()
ERROR 2019-01-21 10:06:48 _log   File "/app/.pyenv/versions/test-3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2049, in _check_banner
ERROR 2019-01-21 10:06:48 _log     'Error reading SSH protocol banner' + str(e)
ERROR 2019-01-21 10:06:48 _log paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR 2019-01-21 10:06:48 _log 
ERROR 2019-01-21 10:06:48 connect 用户Administrator通过webssh连接10.1.19.12失败！原因：Error reading SSH protocol banner
INFO 2019-01-21 10:37:40 _log Connected (version 2.0, client OpenSSH_5.3)
INFO 2019-01-21 10:37:40 _log Authentication (publickey) successful!
INFO 2019-01-21 10:38:16 _log Connected (version 2.0, client OpenSSH_5.3)
INFO 2019-01-21 10:38:16 _log Authentication (publickey) successful!
INFO 2019-01-21 10:38:18 _log [chan 2] Opened sftp connection (server version 3)
INFO 2019-01-21 10:38:20 _log [chan 2] sftp session closed.
INFO 2019-01-21 10:38:44 _log Connected (version 2.0, client OpenSSH_5.3)
INFO 2019-01-21 10:38:44 _log Authentication (publickey) successful!
INFO 2019-01-21 10:38:46 _log [chan 2] Opened sftp connection (server version 3)
INFO 2019-01-21 10:38:48 _log [chan 2] sftp session closed.
